### ISSUE TITLE
Cannot Enable Dev Spaces

### ISSUE THREAD

**Issue by arindamdat** [Azure/dev-spaces#297]
**Describe the bug**
AKS api server is restricted to specific ip ranges and it is in West Europe region. I want to enable dev spaces for this cluster.
So, I added dev spaces public ips for West europe from [here](https://github.com/Azure/dev-spaces/blob/master/public-ips/WestEurope.txt) and updated AKS cluster with this new set of authorized ip ranges.
 `az aks update -g $RESOURCE_GROUP_NAME -n $CLUSTER_NAME --api-server-authorized-ip-ranges $ALL_IP_RANGES`

 
**Expected behavior**
I expected that, after adding azure dev spaces public ip ranges for West Europe region, I'll be able to enable Dev Spaces for this cluster fom portal.
But on azure portal, when I tried Enable Dev space, I received the following error:

> Failed to create a Dev Spaces controller for cluster 'plt-d-euw-aks': Failed to configure container host for Azure Dev Spaces Controller. Unable to reach kube-apiserver. See https://aka.ms/azds-unreachable-kubeapiserver for more information.

 
**Environment Details**
Client used : Azure portal UI

**Comment by amsoedal** [comment]
Hi @arindamdat, 
Thank you for bringing this to our attention! Our IPs recently changed and we had not yet updated the documentation.  Can you try again with the new IPs for West Europe and let us know if it works?
We're sorry for the inconvenience!

**Comment by arindamdat** [comment]
Hi @amsoedal , even after adding the new IPS [51.124.13.220/32,51.124.13.131/32,51.138.52.155/32,51.105.206.105/32,51.105.202.67/32,51.138.52.15/32,51.138.52.179/32] to the list of `api-server-authorized-ip-ranges`, it fails to create controller with the same error "Unable to reach kube-apiserver". Please note that, api server is running as expected and I've tested all my kubectl commands are working.

**Comment by rakeshvanga** [comment]
@arindamdat, Are you able to use your kubectl commands to connect to the api-server and get nodes information?

**Comment by arindamdat** [comment]
Hi @rakeshvanga , yes I can do kubect because my IP is whitelisted to the api server. That's why I suspect the DevSpaces IPs are possibly not correct.

**Comment by rakeshvanga** [comment]
@arindamdat , we have updated the public IPs for the Europe regions. Can you take the latest ones?
Also, make sure that you are specifying all the IPs in the `aks update` call. 
It seems that there is an issue with this IP whitelisting with AKS and I'm also facing a similar issue but for me, kubectl commands are also not working. Working with AKS on-call to investigate the issue.

**Comment by arindamdat** [comment]
@rakeshvanga , the new set of IPs work! Thanks for the support.

**Comment by arindamdat** [comment]
It was too early to close this issue. After updating the latest set of IPs (for west-europe region), only the controller creation succeeded. However, after that, none of the azds commands are not working. For example, `azds space list` shows **operation cancelled**.
@rakeshvanga : however, kubectl commands work well at my end, there is absolutely no issue with that at my end.

**Comment by arindamdat** [comment]
@amsoedal , is there a working example/test somewhere to show that Azure Dev Spaces works when K8s api server is restricted to specific set of IPs?

**Comment by rakeshvanga** [comment]
Hi @arindamdat , these are the other networking requirements for Azure Dev Spaces: https://docs.microsoft.com/en-us/azure/dev-spaces/configure-networking
Are there any other traffic restrictions applied to your cluster?

**Comment by rakeshvanga** [comment]
Hi @arindamdat , The issue has been fixed for west europe region, can you try running the `azds space` commands again now?
No need to create the controller again.

**Comment by arindamdat** [comment]
> Hi @arindamdat , these are the other networking requirements for Azure Dev Spaces: https://docs.microsoft.com/en-us/azure/dev-spaces/configure-networking
> Are there any other traffic restrictions applied to your cluster?

Hi @rakeshvanga other networking considerations might not be a factor in my case, because whenever I open up the api-server by removing all whitelisted IPs everything behaves as expected. It's only when I whitelist IPs (including the one for azds west-europe region), things don't work.

**Comment by arindamdat** [comment]
> Hi @arindamdat , The issue has been fixed for west europe region, can you try running the `azds space` commands again now?
> No need to create the controller again.

Hi @rakeshvanga , it still doesn't work, however, now I am getting a different error from azds cli.
**Command** : `azds space list`
**Output**: `Oops... An unexpected error has occurred. A report of the error will be sent to Microsoft.
For diagnostic information, see Azure Dev Spaces logs at 'C:\Users\arindam.datta\AppData\Local\Temp\Azure Dev Spaces'.
Please include the following Client Request ID when contacting support: 4b67e3fe-2254-443b-b30f-39eeb8a29487`.
**Complete log**:
`2020-04-28T15:14:50.4505982Z | SDK | ERROR | Logging handled exception: Microsoft.Azure.DevSpaces.Client.Exceptions.OperationIdException: {"RequestId":null,"ClientRequestId":"4b67e3fe-2254-443b-b30f-39eeb8a29487","CorrelationRequestId":null,"Request":null,"Response":null,"Format":"Failed to list dev spaces.","Args":[],"Message":"Failed to list dev spaces.","Data":{},"InnerException":{"Request":{"Method":{"Method":"GET"},"RequestUri":"https://azds-cd3cb74d-62b6-427f-bd0d-502e501e6187.weu.azds.io/api/v3.2/Spaces","Properties":{},"Content":null,"Headers":{"x-ms-client-request-id":["4b67e3fe-2254-443b-b30f-39eeb8a29487"],"Accept-Language":["en-US"],"Authorization":["dca2497030d19b74"],"User-Agent":["CLI/1.0.20200407.9"]}},"Response":{"StatusCode":503,"ReasonPhrase":"Service Unavailable","Content":"Service Unavailable","Headers":{"Vary":["Accept-Encoding"],"Date":["Tue, 28 Apr 2020 15:14:36 GMT"],"Content-Length":["19"],"Content-Type":["text/plain; charset=utf-8"]}},"Body":null,"Message":"Operation returned an invalid status code 'ServiceUnavailable'","Data":{},"InnerException":null,"StackTrace":"   at Microsoft.Azure.DevSpaces.ExecService.Client.SpacesOperations.ListSpacesWithHttpMessagesAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken) in E:\\A\\_work\\3013\\s\\src\\execsvc.client.autogen\\SpacesOperations.cs:line 628\r\n   at Microsoft.Azure.DevSpaces.Client.ServiceClients.ExecExceptionStrategy.RunWithHandlingAsync[T](Func`1 func, FailureConfig failureConfig) in E:\\A\\_work\\3013\\s\\src\\client\\Client\\ServiceClients\\ExceptionStrategies\\ExecExceptionStrategy.cs:line 58","HelpLink":null,"Source":"Microsoft.Azure.DevSpaces.ExecService.Client.Autogen","HResult":-2146233088},"StackTrace":null,"HelpLink":null,"Source":null,"HResult":-2146233088}\nOperation context: <json>{"clientRequestId":"4b67e3fe-2254-443b-b30f-39eeb8a29487","correlationRequestId":null,"requestId":null,"userSubscriptionId":"0ee8cf80-8924-4d15-9d41-3b19beb818bd","startTime":"2020-04-28T15:14:29.9935743Z","userAgent":"CLI/1.0.20200407.9","requestHttpMethod":null,"requestUri":null,"apiVersion":"3.2","version":"1.0.20200407.9","requestHeaders":{},"loggingProperties":{"applicationName":"SDK","deviceOperatingSystem":"Microsoft Windows 10.0.18362 ","framework":".NET Core 4.6.26515.07","macAddressHash":"0153f64fac1e9ce2c9591f887feedbd30090e562bf3971474e53ff49d19d301f","processId":20156,"targetEnvironment":"Production","clusterFQDN":"azds-cd3cb74d-62b6-427f-bd0d-502e501e6187.weu.azds.io","resourceGroupName":"plt-d-euw-rg","devSpacesControllerName":"plt-controller"}}</json>
2020-04-28T15:14:50.4795605Z | SDK | TRACE | Event: SpacesServiceClient-List <json>{"properties":{"result":"Failed"},"metrics":{"duration":20450.0}}</json>
`
**From the above log, I noticed that the RequestUri `https://azds-cd3cb74d-62b6-427f-bd0d-502e501e6187.weu.azds.io/api/v3.2/Spaces` is unavailable. What is this Uri about?**

**Comment by rakeshvanga** [comment]
https://azds-<guid>.weu.azds.io is a data plane endpoint of Azure Dev Spaces that helps in debugging your service. The issues you have faced in the morning are transient and it is fixed now. Can you try to list spaces now?

**Comment by arindamdat** [comment]
@rakeshvanga : yes, it's magically resolved now!
